"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['nCoda.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'emulate_shell_environment': True,
    # 'includes': ['fujian', 'abjad', 'lychee', 'shelfex'],
    'packages': ['fujian', 'abjad', 'lychee', 'shelfex'],
    }

setup(
    app=APP,
    data_files=[],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
